server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application:
    name: adote-um-amanha
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ages}
    username: ${DB_USERNAME:ages}
    password: ${DB_PASSWORD:ages}

security:
  jwt:
    secret: ${JWT_SECRET:adote-um-amanha-jwt}
    expiration: ${JWT_EXPIRATION:86400000} # 1 dia em sec
  public:
    path: "/public/**"


