server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application:
    name: adote-um-amanha
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ages}
    username: ${DB_USERNAME:ages}
    password: ${DB_PASSWORD:ages}

security:
  jwt:
    secret: ${JWT_SECRET:adote-um-amanha-jwt}
    expiration: ${JWT_EXPIRATION:86400000} # 1 dia em sec
  public:
    path: "/public/**"

mail:
  smtp:
    host: ${smtp_host:smtp.mailtrap.io}
    port: ${smtp_port:2525}
    user: ${smtp_user:313504c6a12950}
    pass: ${smtp_pass:d6d6d7d4c82ebc}
    conf:
      debug: true